### PR TITLE
Fix : Copyright year_bug

### LINKED ISSUE #87: Copyright Year_Bug
Currently the copyright year is just a copy paste of text using html , 
but it should be dynamic in nature that is it should fetch current year that will be done using java script 
@ANSHIKA-26 assign this issue to me I will fix it . 
I am working under VSOC

### PR DESCRIPTION
**Pull request by Meetjain1**
closes #87 
Fixed the copyright year bug .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
hey , if you are contributing under vsoc , please drop your email , thanks !

**Comment by ANSHIKA-26** [comment]
also , can you show a screenshot of the output as well ?

**Comment by Meetjain1** [comment]
> hey , if you are contributing under vsoc , please drop your email , thanks !

sure meetofficialhere@gmail.com

**Comment by Meetjain1** [comment]
> also , can you show a screenshot of the output as well ?

sure , 
cry2

**Pull request merged**
