### PR TITLE
Creating a Terms & Conditions page

### PR DESCRIPTION
**Pull request by kratik1237**
Creating a Terms & Conditions page is Done #92 @ANSHIKA-26

### CODE REVIEW

**Comment by kratik1237** [comment]
Screenshot (89)
Screenshot (90)
@ANSHIKA-26

**Comment by kratik1237** [comment]
https://github.com/user-attachments/assets/9ec5340c-db36-48d5-b637-611e07e76618

**Comment by kratik1237** [comment]
@ANSHIKA-26

**Comment by kratik1237** [comment]
@ANSHIKA-26  Done

**Comment by ANSHIKA-26** [comment]
@kratik1237

**Comment by kratik1237** [comment]
It is done @ANSHIKA-26

**Pull request merged**
