### PR TITLE
FAQs UI is DONE

### PR DESCRIPTION
**Pull request by kratik1237**
FAQs page is completed for the issue #94

https://github.com/user-attachments/assets/d0f859d1-54ba-4289-acc7-2022d7176a41

### CODE REVIEW

**Comment by kratik1237** [comment]
pls check the pr #101  for the issue #94 @ANSHIKA-26

**Comment by kratik1237** [comment]
Screenshot (81)
Screenshot (82)
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
can you increase width of the whole parent div ? something like this 
image

**Comment by kratik1237** [comment]
sure @ANSHIKA-26

**Comment by kratik1237** [comment]
Screenshot (86)
@ANSHIKA-26 
like this??

**Comment by kratik1237** [comment]
both side change the width ?? @ANSHIKA-26 ,means home page or FAQs page ???

**Comment by kratik1237** [comment]
but i worked in this issue for last 4 days pls give some points @ANSHIKA-26 ??????

**Pull request closed without merging**
