### PR TITLE
Add Best UI Privacy Policy Page and favicon icon

### PR DESCRIPTION
**Pull request by kratik1237**
Add Best UI Privacy Policy Page and favicon icon are done for the issue #91 
Screenshot (88)
@ANSHIKA-26

### CODE REVIEW

**Comment by kratik1237** [comment]
pls check the PR #102 for the issue #91 @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
can i see the video of the page  after u click privacy policy

**Comment by ANSHIKA-26** [comment]
can i see the favicon ?

**Comment by kratik1237** [comment]
image

**Comment by kratik1237** [comment]
Uploading WhatsApp Video 2024-07-16 at 18.50.24_98c08b4e.mp4…

**Comment by kratik1237** [comment]
@ANSHIKA-26

**Pull request closed without merging**
