### PR TITLE
Register Page for the website

### PR DESCRIPTION
**Pull request by kratik1237**
Register Page for the website is DONE for the issue #95 
Screenshot (91)
@ANSHIKA-26

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
you are trying to merge 180 files , most of no use 
1. i need to see where is this register button linked to ?
2. make a video to show point 1 
3.if this page is without a backend , then we really dont need one

**Comment by kratik1237** [comment]
@ANSHIKA-26  

https://github.com/user-attachments/assets/1b28e440-622b-490e-a6a4-fd063d6627e7

**Comment by kratik1237** [comment]
"Yes, the page currently does not have a backend, but I have completed the design. Here are some key points about the design work that has been done:

User Experience (UX):

The form is designed with a user-friendly interface, ensuring a seamless and intuitive experience for users. All fields are clearly labeled, and the layout guides users to fill out the form effortlessly.
Responsive Design:

The form is fully responsive, ensuring it works well on various devices, including desktops, tablets, and smartphones. This is achieved using CSS media queries and flexible grid layouts.
Visual Appeal:

The design follows modern design principles with a clean and aesthetic look. Consistent styling with appropriate use of colors, fonts, and spacing enhances readability and user engagement.
Accessibility:

Accessibility considerations have been incorporated to ensure that the form is usable by people with disabilities. Proper HTML elements and ARIA attributes have been used for compatibility with screen readers.
Form Validation:

Client-side validation is implemented using JavaScript to provide immediate feedback to users, ensuring that all required fields are filled out correctly before submission.
Loading States and Feedback:

Visual feedback mechanisms are in place for form actions, such as showing a loading spinner during submission and displaying success or error messages.
Security Considerations:

While there is no backend, the design ensures that sensitive information is not exposed in URLs or other insecure places.
Scalability:

The design is scalable and can be easily integrated with a backend in the future if needed. The clean and modular structure of the code ensures that adding backend functionality will be straightforward.
These points highlight the quality and thoroughness of the design work, demonstrating that significant effort and attention to detail have been invested in creating a robust frontend. Even without a backend, the design sets a solid foundation for future enhancements and integrations."

**Comment by kratik1237** [comment]
@ANSHIKA-26

**Comment by kratik1237** [comment]
okay @ANSHIKA-26 for your guidence

**Pull request closed without merging**
