### PR TITLE
 Licensing page is complete

### PR DESCRIPTION
**Pull request by kratik1237**
Licensing page is complete for the issue #93 @ANSHIKA-26 
Screenshot (92)
Screenshot (93)

### CODE REVIEW

**Comment by kratik1237** [comment]
pls review the PR #105 for the issue #93 @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
video instead of screenshots

**Comment by kratik1237** [comment]
https://github.com/user-attachments/assets/0f68394e-0873-4fac-b822-ee113f909225

**Comment by kratik1237** [comment]
@ANSHIKA-26

**Pull request merged**
